import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SiteHeader } from "@/components/header/site-header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "rvthaifish.com",
  icons: "@/styles/favicon.ico",
  description: "Generated by create next app"
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="relative flex min-h-screen flex-col items-center">
          <SiteHeader />
          {children}
        </div>
      </body>
    </html>
  );
}
